/**
 * Teardown spec — everything the deep 3D workbench needs, in one object.
 *
 * Berkeley Humanoid Lite is the reference implementation: its spec is assembled
 * from the hand-curated modules (`robot-tree`, `robot-parts`, `project-meta`)
 * and is the default everywhere. Teardowns generated by the evidence pipeline
 * (`lib/teardowns.generated.ts`) supply the same shape from the repository
 * itself, so a generated project and the reference render through identical
 * components and are held to identical rules.
 *
 * `gaps` and `basis` are required for generated specs on purpose: a generated
 * teardown has to state where its geometry and structure came from and what it
 * could not get, rather than looking indistinguishable from a curated one.
 */

import { PROJECT_META } from "./project-meta";
import { ALL_PARTS, type Part } from "./robot-parts";
import { ROBOT_TREE, type TreeNode } from "./robot-tree";
import { REGIONS, regionOfLink, type RegionInfo } from "./robot-view";

export interface TeardownMeta {
  projectId: string;
  version: string;
  embodiment: string;
  reproduction?: {
    probabilityPercent: number;
    band: string;
    confidence: string;
  };
  releaseStates?: readonly { version: string; status: string }[];
}

export interface TeardownSpec {
  id: string;
  name: string;
  repository?: string;
  /** Score from the evidence pipeline; the anchor is 100. */
  score?: number;
  meta: TeardownMeta;
  tree: TreeNode;
  parts: Part[];
  /** GLB with one named node per part/link. */
  modelUrl: string;
  /** Link/joint metadata derived from the released URDF. */
  modelJsonUrl: string;
  regions: RegionInfo[];
  regionOfLink: (link: string) => string;
  /** Where the geometry and the part rows come from. Required when generated. */
  basis: string;
  /** What this repository does not contain. Never empty for generated specs. */
  gaps: string[];
  /** True when the evidence pipeline produced this spec. */
  computed?: boolean;
}

/**
 * What the pipeline emits. Functions cannot cross the generator boundary, so a
 * generated spec carries an explicit link → region table and the registry turns
 * it into the function the viewer wants.
 */
export interface GeneratedTeardown extends Omit<TeardownSpec, "regionOfLink" | "computed"> {
  regionByLink: Record<string, string>;
  /** Always true here; separate field so the emitter cannot silently omit it. */
  generated: true;
}

/** The reference implementation, assembled from the curated modules. */
export const BERKELEY_SPEC: TeardownSpec = {
  // The project id, not ROBOT_TREE.id: the tree's root node is called "root",
  // which is a different namespace from the catalog's project ids.
  id: PROJECT_META.projectId,
  name: "Berkeley Humanoid Lite",
  repository: "https://github.com/HybridRobotics/Berkeley-Humanoid-Lite",
  score: 100,
  meta: PROJECT_META as TeardownMeta,
  tree: ROBOT_TREE,
  parts: ALL_PARTS,
  modelUrl: "/model/robot.glb",
  modelJsonUrl: "/model/robot.json",
  regions: REGIONS,
  regionOfLink,
  basis:
    "手工策展：几何取自官方发布的 URDF 与网格，零件行取自发布版物料清单，" +
    "关节 CAN 编号取自《Joint ID Mapping》文档。",
  gaps: [],
};

export const DEFAULT_SPEC: TeardownSpec = BERKELEY_SPEC;
